### ISSUE TITLE
Any workaround to bypass the Typora's link detection?

### ISSUE THREAD

**Issue by littlebugyang** [a1473838623/Joplin-Typora-images-paste#1]
I just found that Typora would determine the `![image](resources/xxxx.png)` was an invalid url for the image to be pasted, then it would save the image into the Typora image folder.

Does there exist any workaround to apply this project without using another `GET /resources` API referring to the image?

:)

**Comment by a1473838623** [comment]
Using the  joplin web clipper (the post API) to store the image into joplin is necessary(Or you have to store the image into Joplin in the first place, in this case, you just need paste the content(not image)`![image](resources/xxxx.png)`into typora). Based on this, we can pass the typora error "invalid url" by firstly replace the path with "GET /resources" url, then use python script to replace the url with `![image](resources/xxxx.png)`. But I haven't check if there is image saved in the Typora image folder.

**Comment by littlebugyang** [comment]
I didn't realize that there were two scripts to be used together, one for uploading and one for replacing content. It was my mistake to miss the detail of the implementation.

Really suprised and appreciated for you reply. Thanks.

**Comment by littlebugyang** [comment]
I came up with an idea that an alternative workaround was to modify the content of the Clipboard once we uploaded the image successfully. But the drawback is also obvious, only one image can be processed.
